name: hellowWorld
on: workflow_dispatch 
jobs: 
  hello-word-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
